version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - openschools
  app: 
    build: .
    image: node:16
    depends_on: 
      - db
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      NODE_ENV: "production"
      PORT: "5000"
    networks:
      - openschools
networks:
  openschools:
    driver: bridge
volumes:
  pgdata:
    driver: local